# Sponsor button — exibido na sidebar do repo no GitHub.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [LucasHiago]
patreon: Asteroth
custom: ["https://asteroth.com.br"]
